name    'puppetlabs-corosync'
version '0.1.0'
source 'https://github.com/puppetlabs/puppetlabs-corosync.git'
author 'puppetlabs'
license 'APL 2.0'
summary 'Sets up and manages Corosync'
description 'This module is a set of manifests and types/providers for quickly setting up highly available clusters using Corosync'
project_page 'https://github.com/puppetlabs/puppetlabs-corosync'
dependency 'puppetlabs/stdlib', '>= 2.3.1'
