#!/bin/bash
#
#
#  Generic OCF RA that just sets the master/slave state so we can use it.
#  The state is read by facter and used during a puppet agent run. 
#
# Copyright (c) 2012 Puppet Labs, LLC, All Rights Reserved.
#

#######################################################################
# Initialization:

. ${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs

#######################################################################

meta_data() {
  cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="ppdata" version="0.0.1">
<version>0.0.1</version>

<longdesc lang="en">
Manages the data associated with master/slave CA relationships.
</longdesc>
<shortdesc lang="en">Puppet promotion/demotion kicker</shortdesc>

<actions>
<action name="start"   timeout="1" />
<action name="stop"    timeout="1" />
<action name="promote" timeout="600" />
<action name="demote"  timeout="600" />
<action name="monitor" timeout="20" interval="20" depth="0" role="Slave" />
<action name="monitor" timeout="20" interval="10" depth="0" role="Master" />
</actions>
</resource-agent>
END
}

#######################################################################

_usage() {
cat <<END
usage: $0 {start|stop|monitor|meta-data}

Expects to have a fully populated OCF RA-compliant environment set.
END
}

ppk_start() {
  return $OCF_SUCCESS
}

ppk_stop() {
  return $OCF_SUCCESS
}

ppk_monitor() {
  return $OCF_SUCCESS
}

ppk_promote() {
  return $OCF_SUCCESS
}

ppk_demote() {
  return $OCF_SUCCESS
}

case $__OCF_ACTION in
meta-data)	meta_data
		exit $OCF_SUCCESS
		;;
start)		ppk_start;;
stop)		ppk_stop;;
monitor)	ppk_monitor;;
promote)        ppk_promote;;
demote)         ppk_demote;;
usage|help)	ppk_usage
		exit $OCF_SUCCESS
		;;
*)		pec_usage
		exit $OCF_ERR_UNIMPLEMENTED
		;;
esac
rc=$?
ocf_log debug "${OCF_RESOURCE_INSTANCE} $__OCF_ACTION : $rc"
exit $rc

